/**
 * Copy the live web PWA into native/www for Capacitor.
 * Source of truth stays at the repo root (GitHub Pages). native/www is generated.
 */
import { cpSync, mkdirSync, rmSync, existsSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const nativeRoot = join(__dirname, "..");
const repoRoot = join(nativeRoot, "..");
const www = join(nativeRoot, "www");

const COPY = ["index.html", "sw.js", "css", "js", "assets"];

function assertSource() {
  if (!existsSync(join(repoRoot, "index.html"))) {
    console.error("[sync-web] Missing repo-root index.html");
    process.exit(1);
  }
}

assertSource();
rmSync(www, { recursive: true, force: true });
mkdirSync(www, { recursive: true });

for (const name of COPY) {
  const from = join(repoRoot, name);
  if (!existsSync(from)) {
    console.warn(`[sync-web] skip missing: ${name}`);
    continue;
  }
  cpSync(from, join(www, name), { recursive: true });
  console.log(`[sync-web] copied ${name}`);
}

/**
 * Mark native shell in www only (repo-root index.html unchanged).
 * Capacitor injects window.Capacitor at runtime inside the iOS WebView.
 */
const indexPath = join(www, "index.html");
let html = readFileSync(indexPath, "utf8");
const marker = "<!-- capacitor-native-marker -->";
if (!html.includes(marker)) {
  const snippet = `${marker}
<script>
(function () {
  function mark() {
    try {
      if (window.Capacitor && window.Capacitor.isNativePlatform && window.Capacitor.isNativePlatform()) {
        document.documentElement.classList.add("capacitor-native");
      }
    } catch (e) { /* ignore */ }
  }
  mark();
  document.addEventListener("DOMContentLoaded", mark);
  window.addEventListener("load", mark);
})();
</script>
`;
  html = html.replace("</head>", `${snippet}</head>`);
  writeFileSync(indexPath, html);
  console.log("[sync-web] tagged www/index.html for native detection");
}

writeFileSync(
  join(www, ".generated"),
  "Generated by native/scripts/sync-web.mjs — do not edit. Source of truth is the repo root.\n"
);

console.log("[sync-web] done → native/www");
